<?xml version="1.0"?>
<package format="3">
  <name>dp_realsense</name>
  <version>0.0.1</version>
  <description>Launch wrappers for Intel RealSense D435 within DP-NeTSDF.</description>
  <maintainer email="manueljunior14.mj@gmail.com">Manuel Junior</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>realsense2_camera</exec_depend>
</package>
