<?xml version="1.0"?>
<package format="3">
  <name>dp_visualizer</name>
  <version>0.0.1</version>
  <description>Visualization configs for DP-NeTSDF.</description>
  <maintainer email="manueljunior14.mj@gmail.com">Manuel Junior</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>

  <exec_depend>rviz2</exec_depend>
</package>
